#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Customization script to detect and modify board hardware feature list, based
# on /etc/hardware_features.xml. Read go/arc-board-features for how to use this
# file.

die() {
  echo "ERROR: $@" >&2
  exit 1
}

modify_feature() {
  local file="$1"
  local feature="$2"
  local pattern="$3"
  local replace="$4"

  # Assume each feature is already defined in one line.
  sed -e "/name=\"${feature}\"/s/${pattern}/${replace}/" -i "${file}"
}

enable_feature() {
  modify_feature "$@" "<unavailable-feature " "<feature "
}

disable_feature() {
  modify_feature "$@" "<feature " "<unavailable-feature "
}

detect_accelerometer() {
  grep -q "cros-ec-accel" /sys/bus/iio/devices/iio\:device*/name
}

detect_gyro() {
  grep -q "cros-ec-gyro" /sys/bus/iio/devices/iio\:device*/name
}

detect_multicamera() {
  local multi_camera
  multi_camera="$(/usr/bin/generate_camera_profile --detect-multi-cameras)"
  test "${multi_camera}" = "1"
}

detect_touchscreen() {
  grep -q "[Tt]ouchscreen" /sys/class/input/input*/name
}

main() {
  if [ "$#" != 1 ]; then
    die "Usage: board_hardware_features PATH_TO_PLATFORM_XML"
  fi
  local file="$1"

  if ! detect_accelerometer; then
    echo "Disable accelerometer feature."
    disable_feature "${file}" android.hardware.sensor.accelerometer
  else
    echo "Enable accelerometer feature."
    enable_feature "${file}" android.hardware.sensor.accelerometer
  fi

  if ! detect_gyro; then
    echo "Disable gyro feature."
    disable_feature "${file}" android.hardware.sensor.gyroscope
  else
    echo "Enable gyro feature."
    enable_feature "${file}" android.hardware.sensor.gyroscope
  fi

  if ! detect_multicamera; then
    echo "Disable back camera features."
    disable_feature "${file}" android.hardware.camera
  else
    echo "Enable back camera features."
    enable_feature "${file}" android.hardware.camera
  fi

  if ! detect_touchscreen; then
    echo "Disable touchscreen features."
    disable_feature "${file}" android.hardware.touchscreen
    disable_feature "${file}" android.hardware.touchscreen.multitouch
    disable_feature "${file}" android.hardware.touchscreen.multitouch.distinct
    disable_feature "${file}" android.hardware.touchscreen.multitouch.jazzhand
  else
    echo "Enable touchscreen features."
    enable_feature "${file}" android.hardware.touchscreen
    enable_feature "${file}" android.hardware.touchscreen.multitouch
    enable_feature "${file}" android.hardware.touchscreen.multitouch.distinct
    enable_feature "${file}" android.hardware.touchscreen.multitouch.jazzhand
  fi

  # Model-specific overrides
  model_hardware_features="$(cros_config --abspath /arc hw-features)"

  if [ -n "${model_hardware_features}" ]; then
    if [ -x "${model_hardware_features}" ]; then
       echo "Invoking model-specific file: ${model_hardware_features}"
      "${model_hardware_features}" "${file}"
    fi
  fi
}

main "$@"